apiVersion: apps/v1
kind: Deployment
metadata:
  name: i2btech-reto-app3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: i2btech-reto-app3
  template:
    metadata:
      labels:
        app: i2btech-reto-app3
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.app.port }}
          volumeMounts:
            - name: logs
              mountPath: /app/logs

        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: htpasswd
              mountPath: /etc/nginx/.htpasswd
              subPath: .htpasswd

      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: i2btech-reto-app-pvc3

        - name: nginx-conf
          configMap:
            name: i2btech-reto-app-nginx-conf

        - name: htpasswd
          secret:
            secretName: i2btech-reto-app-basic-auth
