apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: i2btech-reto-app-ingress
  namespace: i2btech-reto-app-ns
spec:
  rules:
    - host: 172-68-0-6.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: i2btech-reto-app3
                port:
                  number: 443
