apiVersion: v1
kind: ConfigMap
metadata:
  name: i2btech-reto-app-nginx-conf
data:
  default.conf: |
    server {
      listen 80;
      server_name {{ .Values.domain }};
      return 301 https://$host$request_uri;
    }

    server {
      listen 443 ssl;
      server_name {{ .Values.domain }};

      ssl_certificate /etc/nginx/certs/tls.crt;
      ssl_certificate_key /etc/nginx/certs/tls.key;

      location / {
        proxy_pass http://localhost:{{ .Values.app.port }};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
      }

      location /private {
        auth_basic "Restricted";
        auth_basic_user_file /etc/nginx/.htpasswd;
        proxy_pass http://localhost:{{ .Values.app.port }};
      }
    }
