apiVersion: v1
kind: ConfigMap
metadata:
  name: i2btech-reto-app-nginx-conf
data:
  default.conf: |
    server {
      listen 80;
      server_name {{ .Values.domain }};

      location / {
        proxy_pass http://localhost:{{ .Values.app.port }};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
      }

      location /private {
        auth_basic "Restricted";
        auth_basic_user_file /etc/nginx/.htpasswd;
        proxy_pass http://localhost:{{ .Values.app.port }};
      }
    }