apiVersion: v1
kind: Service
metadata:
  name: i2btech-reto-app2
spec:
  type: {{ .Values.service.type }}
  selector:
    app: i2btech-reto-app2
  ports:
    - name: https
      port: {{ .Values.service.port }}
      targetPort: 443
