image:
  repository: $IMAGE_REPOSITORY
  tag: "latest"
  pullPolicy: IfNotPresent

app:
  port: 3000

service:
  type: ClusterIP
  port: 443

persistence:
  logsPath: "/var/i2btech-logs"

domain: "172.68.0.6.nip.io"